### ISSUE TITLE
Incident Workflows

### ISSUE THREAD

**Issue by moshloop** [flanksource/incident-commander#169]
i.e 

```yaml
stages:
- name: triage
- name: open
- name: mitigated
- name: resolved
- name: closed
```
