### ISSUE TITLE
Incident rules

### ISSUE THREAD

**Issue by moshloop** [flanksource/incident-commander#46]
Automatically open and close incidents based on health checks:

- Provide an option to filter health checks (components in yaml below).
- Static responders (see yaml below) or responders based on topology (https://github.com/flanksource/canary-checker/blob/master/pkg/db/migrations/3_topology.sql#L39)
- Open + Close timeouts - How long do the health checks need to be firing / not-firing before opening-closing

```yaml
kind: IncidentRule
spec: 
   name: Production Database team
   incident: 
   components:
     - type: Database
        selector:
            env: Production

   rule:
     - open_for: 

   responder:
     -  jira:
        Team Name: DB_TEAM
      	priority: high
         ...
```

[Not part of MVD]
- Inhibit other health checks / Grouping [Out of scope: to be moved to another issue]
