### ISSUE TITLE
Playbooks - GitOps Actions

### ISSUE THREAD

**Issue by moshloop** [flanksource/incident-commander#490]
Update files in git repos

**Comment by moshloop** [comment]
See https://github.com/flanksource/tenant-controller/tree/main/pkg/git

```
params:
  - name: namespace
steps:
   - gitops:
          repo: 
              url: ..
              connection: ...
          commit:
            author: bot
            name: abc
          pr: # if connection type is github or azuredevops then open a new pr
            title: ABC
            tags: 
              - abc 
              - efg
          patches:
            # insert the new kustomization into the root
            - path: namespaces/kustomization.yaml
              yq: '.resources += "{{.namespace}}"'
            - path: resources.json
              jq: '...'
          files:
              namespaces/{{.namespace}-ns.yaml: $delete # cleanup old files
              namespaces/{{.namespace}/ns.yaml: |
                apiVersion: v1
                kind: Namespace
                metadata:
                  name:  {{.namespace}}
              namespaces/{{.namespace}/kustomization.yaml: |
                  bases:
                    - ns.yaml
```
