### ISSUE TITLE
Playbooks - Run on event

### ISSUE THREAD

**Issue by moshloop** [flanksource/incident-commander#508]
e.g. When a  health check or component becomes unhealth

```YAML
on:
  canary:
    - labels: # match labels
      #CEL expression - will need access to the check 1h summary of pass/faill/latency e.g.
      filter: status == 'fail' && summary.failed >  3
      event:   failed
  component:
    - labels: # match labels
      #CEL expression - will need access to the check 1h summary of pass/faill/latency e.g.
      filter: status == 'fail' && summary.failed >  3
      event:   failed
```

**Comment by moshloop** [comment]
@yashmehrotra  wdyt ^

**Comment by yashmehrotra** [comment]
@moshloop I'm in for the feature. I think we should also allow these to be run manually via UI where components/checks etc. can be taken as user input

Thinking in terms of a job runner like rundeck or jenkins, where certain tedious (but automatable) daily tasks can be performed

**Comment by moshloop** [comment]
@yashmehrotra - yeh thats what we are going for

@adityathebe I don't think we can notify in that way as listeners are per session, if the incident commander is down when notification runs it will be lost. 

We could change the current logic

1. Recieve an event
2. Run all sync consumers (Can only update the DB)
3. Run a a single async consumer (If more than 1 async consumber then we create new events for them, that are generated in step 2)

e.g.

When check.failed we can insert new notifications and new playbook runs - If there are errors on the new notification or playbook run insertion, then then the transaction fails and we rollback everything -  The only downside here is that if there are errors ina notification filter then it would previent a playbook run insertion (and vice-versa).   Although by using CEL and precompiling and executing the filters we can pick these up before they are added as a consumer

**Comment by adityathebe** [comment]
@moshloop I think we should not care whether the async consumers error out or not. We can create a `preconsumeFunc` for event consumers that runs before an event is consumed. We don't care whether `preconsumeFunc` errors out or not so it doesn't hinder the main `ProcessBatchFunc`. 

Examples: of preconsumeFunc would be
- for events "incident.responder.added" & "incident.responder.removed", it would create a new event
- for events "check.passed" & "check.failed", it would create a new Playbook run.

The downside would be that anything in `preconsumeFunc` wouldn't be retried on failure. Assuming that these are not crucial tasks, we can take the chances. 

If it's a crucial task that needs retries then I think that warrants its own event. For example: we could have one `check.passed` event in the queue and another `playbook.check.passed` event as well created by the same trigger.

**Comment by adityathebe** [comment]
yea we could potentially missed out on events although the chances are extremely minuscule. I don't see a reason why the run consumer would fail to receive an event for the playbook. If the run fails for some reason it is not retried though which I think is fine; as you said in the meeting.

>  if there are no playbooks that need to fire, then we are creating those events for nothing and adding db load.

ya good point

> If we rename presonsumeFunc to handleSyncEvents (Which are only allowed to read/write to the db) and then retry the event if any sync events fail, I think we will have a system that is still 100% correct

Oh I understand what you were trying to say now. So we can still have a `100% correct` system. 
What I personally do not like about this is that the execution is still sequential and any error in the sequence would needlessly block other succeeding consumers.

Additionally, the requirement for `handleSyncEvents` to only allow read/write operations to the db poses two considerations:
- a slightly limiting design
- Going forward, it's essential to always bear in mind that `handleSyncEvents` must avoid executing tasks with side effects.

***

The ideal solution would be to have a single event in the queue, but then have the consumers work in isolation. So if there are 10 different consumers for a single event,
- we have one record for the event in the db
- each consumer maintains its retries and attempt date individually.

Which leads me to think we should probably break `event_queue` table to `event_queue` and `event_attempts`.

**Comment by adityathebe** [comment]
Alternative


```YAML
on:
  check.failed:
    - filter: summary.failed < 2
      labels:
        env: prod
    - filter: summary.failed >  3
      labels:
        env: dev
  check.pass:
    - filter: summary.failed < 2
      labels:
        env: prod
  component.info:
      - filter: component.type == 'application'
  component.healthy:
      - filter: component.namespace == 'default'

```
