### ISSUE TITLE
Group mapping

### ISSUE THREAD

**Issue by moshloop** [flanksource/incident-commander#625]
* Add an optional groups attribute to the kratos identity schema: https://github.com/flanksource/mission-control-chart/blob/main/chart/files/kratos-identity-schema.json
e.g.

schema:
```yaml
 "groups": {
          "type": "array",
          "title": "groups",
          "items": {
            "type": "string"
          }
        }
```

data mapper:

```jsonnet

// Issuer Url: <Okta domain url>
// scopes: email, profile, openid

local claims = std.extVar('claims');
{
  identity: {
    traits: {
      email: claims.email,
      first_name: claims.first_name,
      last_name: claims.last_name,
      [if "groups" in claims.raw_claims then "groups" else null]: claims.raw_claims.groups,
    },
  },
}
```
- Add cel script command line argument for mapping an identity to a role - pass in the identity
e.g.

```
if 'some group id or name' in inentity.groups then "admin" else "viewer"
```
