### ISSUE TITLE
Playbook - Webhooks

### ISSUE THREAD

**Issue by moshloop** [flanksource/incident-commander#662]
```

on: 
    webhook:
             url: # webhook path
             authentication:
                  github:
                         https://docs.github.com/en/webhooks/using-webhooks/validating-webhook-deliveries
                  svix:
                         secret: # see https://github.com/flanksource/tenant-controller/blob/main/pkg/tenant/webhook_verify.go#L57
                  basic:
                          user:
                          pass:
                   jwt:
                      jwksUri: #...
actions:
     exec: echo {{.payload}} {{.headers}}
```
