### ISSUE TITLE
Teams

### ISSUE THREAD

**Issue by moshloop** [flanksource/incident-commander#69]
Teams DB: 
- 

Defining ownership of components and attaching responders to them. 

```yaml
kind: Team
spec: 
   name: Production Database team
   incident: 
   components:
     - type: Database
        selector:
            env: Production
   responder:
     -  serviceNow:
           Team Name: DB_TEAM
      # Email / Pager Duty / Slack etc...
```
   
Would be useful in future for incident rules. E.g.
Create an incident if a component becomes unhealthy and add the team as responder to the incident.

See: https://github.com/flanksource/incident-commander/issues/46
